#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" == "main" ]; then
  echo "you can't commit to the main branch."
  exit 1
fi

if [ "$branch" == "develop" ]; then
  echo "you can't commit to the develop branch."
  exit 1
fi

npm run prettier
npm run lint
